### ISSUE TITLE
Fix the SignUp.js

### ISSUE THREAD

**Issue by Martincho2003** [Martincho2003/Social-network#30]
In the html form u have to add two more input - "Username" and "Confirm password" and i want to sent them in the json for the register.
Also please send the two passwords with "password1" and "password2" in the json

**Comment by Martincho2003** [comment]
if the register is successfull I send you: 
{"status" : "successfull"}
if not:
{"status" : "unsuccessfull",
"error": "the real error"}

**Comment by marto55** [comment]
we done here
